import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Inda",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="mx-45 my-20 max-2xl:mx-20 max-sm:mx-10 max-sm:my-10">
        <div>
          <h1 className="text-6xl w-full font-extrabold text-[#101820] mb-10">
            Property Listings Management
          </h1>
          <nav>
            <Link href="/adminInputs" className="font-bold mx-10 ml-0">
              Admin Inputs
            </Link>
            <Link href="/" className="font-bold mx-10 ">
              Auto Calculated
            </Link>
            <Link href="/" className="font-bold mx-10">
              AI Summaries
            </Link>
            <Link href="/" className="font-bold mx-10">
              Reviews
            </Link>
            <hr className="w-full border-1 mt-5 border-top:none" />
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
